main: com.github.mrko900.blockanim.BlockAnimPlugin
name: mplug
version: 0.1
author: mrko900
api-version: '1.21'
commands:
  newanim:
    usage: /<command>
  savephase:
    usage: /<command> [duration]
  saveanim:
    usage: /<command> [name]
  playanim:
    usage: /<command> [name]
  stopanim:
    usage: /<command> [name]
