main: com.github.mrko900.blockanim.BlockAnimPlugin
name: mplug
version: 0.1
author: mrko900
api-version: '1.21'
commands:
  anim:
    usage: Type /<command> help for help.
    aliases:
      - blockanim
